
include:
  - ./ldap/docker-compose.yml
  - ./mailhog/docker-compose.yml
  - ./postgres/docker-compose.yml

services:
  realm-setup:
    extends:
      file: ./keycloak/docker-compose.yml
      service: realm-setup

  keycloak:
    extends:
      file: ./keycloak/docker-compose.yml
      service: keycloak
    env_file:
      - ./.env
    ports: !reset []
    depends_on:
      realm-setup:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      mailhog:
        condition: service_healthy
      openldap:
        condition: service_healthy

  # I can use this if I want to run the script after the services have started
  keycloak_setup:
    container_name: keycloak_setup
    image: appropriate/curl:latest
    env_file:
      - ./keycloak/.env
    depends_on:
      keycloak:
        condition: service_healthy
    entrypoint:
      - "/bin/sh"
      - "-c"
      - |
        # Install jq for JSON processing
        apk add --no-cache jq
        
        # Make the configuration script executable
        chmod +x /tmp/configure-keycloak.sh
        
        # Run the configuration script
        /tmp/configure-keycloak.sh
    volumes:
      - ./keycloak/configure-keycloak.sh:/tmp/configure-keycloak.sh
    restart: "no"
    tty: false
    networks:
      - keycloak_network

  apache_http_server:
    extends:
      file: ./apache-server/docker-compose.yml
      service: apache_http_server
    env_file:
      - ./.env
    depends_on:
      keycloak:
        condition: service_healthy

volumes:
  keycloak_data: