
include:
  - ./ldap/docker-compose.yml
  - ./mailhog/docker-compose.yml
  - ./postgres/docker-compose.yml

services:
  realm-setup:
    extends:
      file: ./keycloak/docker-compose.yml
      service: realm-setup

  keycloak:
    extends:
      file: ./keycloak/docker-compose.yml
      service: keycloak
    ports: !reset []
    depends_on:
      realm-setup:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      mailhog:
        condition: service_healthy
      openldap:
        condition: service_healthy

  keycloak_setup:
    extends:
      file: ./keycloak/docker-compose.yml
      service: keycloak_setup

  apache_http_server:
    extends:
      file: ./apache-server/docker-compose.yml
      service: apache_http_server
    depends_on:
      keycloak:
        condition: service_healthy

volumes:
  keycloak_data: