services:
  openldap:
    image: bitnami/openldap:2.6.10
    container_name: ${LDAP_HOST_NAME}
    env_file:
      - ./.env
    ports:
      - "${LDAP_PORT:-1389}:1389"
      - "${LDAPS_PORT:-1636}:1636"
    volumes:
      - ldap_data:/bitnami/openldap
      - ./sample.ldif:/ldifs/sample.ldif # This is where the custom ldifs are loaded from
      - ./scripts/healthcheck.sh:/usr/local/bin/healthcheck.sh:ro
      - ../certs/end_entity/openldap/certificate.pem:/opt/bitnami/openldap/certs/certificate.pem
      - ../certs/end_entity/openldap/private_key.pem:/opt/bitnami/openldap/certs/private_key.pem
      - ../certs/end_entity/openldap/intermediate_and_leaf_chain.bundle:/opt/bitnami/openldap/certs/intermediate_and_leaf_chain.bundle
      - ../certs/certificate_authority/certificate_chains/root_and_intermediate_chain.bundle:/usr/local/share/ca-certificates/ca.crt
    post_start:
      - command: |
          sh -c "
            chown 1001:0 /usr/local/share/ca-certificates/ca.crt && \
            chmod 644 /usr/local/share/ca-certificates/ca.crt && \

            chown 1001:0 /opt/bitnami/openldap/certs/certificate.pem && \
            chown 1001:0 /opt/bitnami/openldap/certs/private_key.pem && \
            chown 1001:0 /opt/bitnami/openldap/certs/intermediate_and_leaf_chain.bundle && \

            chmod 644 /opt/bitnami/openldap/certs/certificate.pem && \
            chmod 600 /opt/bitnami/openldap/certs/private_key.pem && \
            chmod 644 /opt/bitnami/openldap/certs/intermediate_and_leaf_chain.bundle && \

            update-ca-certificates
          "
        user: root
    healthcheck:
      test: ["CMD-SHELL", "sh /usr/local/bin/healthcheck.sh"]
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: ${HEALTHCHECK_TIMEOUT:-10s}
      retries: ${HEALTHCHECK_RETRIES:-5}
    networks:
      - keycloak_network

  phpadmin:
    image: osixia/phpldapadmin:stable
    container_name: ${PHP_ADMIN_HOST_NAME}
    env_file:
      - ./.env
    ports:
      - "${PHP_LDAPADMIN_PORT:-6443}:80"
    depends_on:
      openldap:
        condition: service_healthy
    volumes:
      - phpldapadmin_data:/var/www/phpldapadmin
      - ./scripts/phpadmin_entrypoint.sh:/usr/local/bin/entrypoint.sh:ro
      - ../certs/certificate_authority/certificate_chains/root_and_intermediate_chain.bundle:/container/service/ldap-client/assets/certs/${PHPLDAPADMIN_LDAP_CLIENT_TLS_CA_CRT_FILENAME}
    entrypoint: [ "sh", "/usr/local/bin/entrypoint.sh" ]
    healthcheck:
      test: [
        "CMD",
        "php",
        "-r",
        "if (@file_get_contents('http://localhost:80')) exit(0); else exit(1);"
      ]
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: ${HEALTHCHECK_TIMEOUT:-10s}
      retries: ${HEALTHCHECK_RETRIES:-5}
    networks:
      - keycloak_network

volumes:
  ldap_data:
  phpldapadmin_data:

networks:
  keycloak_network:
    driver: bridge
    name: keycloak_network
