
services:
  openldap:
    image: osixia/openldap:stable
    container_name: ${LDAP_HOST_NAME}
    environment:
      LDAP_DOMAIN: ${LDAP_DOMAIN}
      LDAP_BASE_DN: ${LDAP_BASE_DN}
      LDAP_ORGANISATION: ${LDAP_ORGANISATION}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      LDAP_CONFIG_PASSWORD: ${LDAP_CONFIG_PASSWORD}
      LDAP_TLS: ${LDAP_TLS:-"false"}
      LDAP_REPLICATION: ${LDAP_REPLICATION:-"false"}
      LDAP_TLS_ENFORCE: ${LDAP_TLS_ENFORCE:-"false"}
      LDAP_DEFAULT_USERNAME: ${LDAP_DEFAULT_USERNAME:-""}
      LDAP_DEFAULT_PASSWORD: ${LDAP_DEFAULT_PASSWORD:-""}
    ports:
      - "${LDAP_PORT:-389}:389"
      - "${LDAPS_PORT:-636}:636"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    healthcheck:
      test: ["CMD", "ldapsearch", "-x", "-b", "${LDAP_BASE_DN}", "-D", "cn=admin,${LDAP_BASE_DN}", "-w", "${LDAP_ADMIN_PASSWORD}"]
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: ${HEALTHCHECK_TIMEOUT:-10s}
      retries: ${HEALTHCHECK_RETRIES:-5}
    networks:
      - keycloak_network

volumes:
  ldap_data:
  ldap_config:

networks:
  keycloak_network:
    driver: bridge  # Creates a new bridge network for this service
    name: keycloak_network  # This will match the name in the main compose file