services:
  openldap:
    image: bitnami/openldap:2.6.10
    container_name: ${LDAP_HOST_NAME}
    env_file:
      - ./.env
    ports:
      - "${LDAP_PORT:-1389}:1389"
      - "${LDAPS_PORT:-1636}:1636"
    volumes:
      - ldap_data:/bitnami/openldap
      - ./healthcheck.sh:/usr/local/bin/healthcheck.sh:ro
    healthcheck:
      test: ["CMD-SHELL", "/usr/local/bin/healthcheck.sh"]
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: ${HEALTHCHECK_TIMEOUT:-10s}
      retries: ${HEALTHCHECK_RETRIES:-5}
    networks:
      - keycloak_network

  phpadmin:
    image: osixia/phpldapadmin:stable
    container_name: ${PHP_ADMIN_HOST_NAME}
    env_file:
      - ./.env
    ports:
      - "${PHP_LDAPADMIN_PORT:-6443}:80"
    depends_on:
      openldap:
        condition: service_healthy
    volumes:
      - phpldapadmin_data:/var/www/phpldapadmin
    healthcheck:
      test: [
        "CMD",
        "php",
        "-r",
        "if (@file_get_contents('http://localhost:80')) exit(0); else exit(1);"
      ]
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: ${HEALTHCHECK_TIMEOUT:-10s}
      retries: ${HEALTHCHECK_RETRIES:-5}
    networks:
      - keycloak_network

volumes:
  ldap_data:
  phpldapadmin_data:

networks:
  keycloak_network:
    driver: bridge
    name: keycloak_network
