services:
  # Apache HTTP Server service acting as a reverse proxy
  # It forwards requests to Keycloak using the ProxyPass directive.
  # The ProxyPassReverse ensures that response headers from Keycloak
  # are properly routed back to the client.
  apache_http_server:
    image: httpd:2.4
    container_name: ${HTTPD_CONTAINER_NAME}
    env_file:
      - ./.env
    volumes:
      - ./logs:/usr/local/apache2/logs
      - ./startup_script.sh:/usr/local/bin/startup_script.sh
      # Custom Apache config file - This will configure Apache to act as a reverse proxy for Keycloak
      - ./conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./conf/keycloak-reverse-proxy.conf:/usr/local/apache2/conf/keycloak-reverse-proxy.conf
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "(chmod +x /usr/local/bin/startup_script.sh && /usr/local/bin/startup_script.sh) || echo 'startup_script.sh failed'"
    networks:
      - keycloak_network
    ports:
      - "${HTTPD_PORT:-80}:80"
    restart: always
    healthcheck:
      test: [ "CMD", "test", "-e", "/proc/net/tcp" ]
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: ${HEALTHCHECK_TIMEOUT:-10s}
      retries: ${HEALTHCHECK_RETRIES:-5} #ignore the intellij error

networks:
  keycloak_network:
    driver: bridge  # Creates a new bridge network for this service
    name: keycloak_network  # This will match the name in the main compose file
